runtime: php81
service: api
handlers:
  # Serve static files as static resources.
  - url: /(.+\.(gif|png|jpg|css|js|ico|woff|ttf|eot|svg))$
    static_files: public/\1
    upload: public/(.+\.(gif|png|jpg|css|js|ico|woff|ttf|eot|svg))$
    secure: always

  # Serve your app through index.php for non-static content.
  - url: /.*
    script: auto
    secure: always